# 服务器配置
server:
  port: 8888

# 应用名称
spring:
  application:
    name: gis-hangar-placement

# 日志配置
logging:
  level:
    com.gis: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
